---
name: Create a Release Tag
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. 224.1.0)'
        required: true
      createStgTag:
        description: 'Create STG Tag.'
        type: boolean
      createPrdTag:
        description: 'Create PRD Tag.'
        type: boolean

jobs:
  tag:
    name: Tag
    if: ${{ github.base_ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout_source
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: "v${{ github.event.inputs.version }}"
          message: "Release ${{ github.event.inputs.version }}"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Staging Tag
        uses: negz/create-tag@v1
        if:  ${{ github.event.inputs.createStgTag == 'true' }} 
        with:
          version: "v${{ github.event.inputs.version }}-STG"
          message: "Release ${{ github.event.inputs.version }} for Staging"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Production Tag
        uses: negz/create-tag@v1
        if:  ${{ github.event.inputs.createPrdTag == 'true' }} 
        with:
          version: "v${{ github.event.inputs.version }}-PRD"
          message: "Release ${{ github.event.inputs.version }} for Prod"
          token: ${{ secrets.GITHUB_TOKEN }}
